### ISSUE TITLE
Add ability to select private fine-tuned models

### ISSUE THREAD

**Issue by Colin7780** [replicate/reflux#1]
implement a feature that allows users to select and use their own private fine-tuned models

**Comment by Pwntus** [comment]
Hey @Colin7780 this is now added in 911ce96adbd3368f99796ec9b0a6003422a0d245 when you search for fine-tunes:

<img width="565" alt="Screenshot 2024-09-02 at 22 19 28" src="https://github.com/user-attachments/assets/022f6eec-ee1d-4eb8-9b10-a6026f6fcdc8">
